---
title: "DataProcessing"
author: "Katy Miles"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
# Load in libraries
library(tidyverse)
library(readxl)
library(lme4)
library(emmeans)
library(openxlsx)
library(ggpubr)
library(performance)
library(stringr)
```

## Data Processing

```{r}
# read in data
raw_data_sh1 = read_excel("Study Stats Platinum_Final_2-2-24_KM_3-6-24.xlsx")

raw_data_sh2 = read_excel("Study Stats Platinum_Final_2-2-24_KM_3-6-24.xlsx", sheet = "ACTIVITY")

# Set response variables of interest
response_variables = c("OGA.BWD_AL", "SOS", "CSOM.ACT(MEAN)", 
                       "CSOM.BEHAV(MEAN)", "CBPI.PSS",
                       "CBPI.PIS", "CBPI.QOL", "SED_MIN/DAY", "LIGHT_MIN/DAY",
                        "VIG_MIN/DAY","Total Daily Activity Count")


## Get treatment mapping
map_treatment = function(patient) {
  t1 = raw_data_sh2 %>%
    filter(`Enroll #` == patient, 
           `B1 - T1 - B2 - T2` == "T1_1")
  t2 = raw_data_sh2 %>%
    filter(`Enroll #` == patient, 
           `B1 - T1 - B2 - T2` == "T2_1")

  return(c(rep(t1[1,]$`Supplement Administered`, 3), 
             rep(t2[1,]$`Supplement Administered`, 3)))
}

## Get treatment mapping
map_grouping = function(patient) {
  t1 = raw_data_sh2 %>%
    filter(`Enroll #` == patient, 
           `B1 - T1 - B2 - T2` == "T1_1")
  group = t1[1,]$`Supplement Administered`
  return(rep(group, 6))
}

treatment = unlist(map(unique(raw_data_sh2$`Enroll #`), map_treatment))
grouping = unlist(map(unique(raw_data_sh2$`Enroll #`), map_grouping))

# Code visits in terms of baseline, post1, post2
## Visits 2 and 5 will be coded as baseline
## Visits 3 and 6 will be coded as post1
## Visits 4 and 7 will be coded as post2
## Visit 1 will be coded as intro and dropped for purposes of analysis

## Just need analysis on OG_AL
clean_data_sh1 = raw_data_sh1 %>%
  rename(Patient = `Enroll #`) %>%
  mutate(Time = ifelse(Visit == 2 | Visit == 5, "baseline",
                        ifelse(Visit == 3 | Visit == 6, "post1",
                        ifelse(Visit == 4 | Visit == 7, "post2", "intro")))) %>%
  filter(Time != "intro") %>%   # Drop visit 1 as not used in analysis
  select(-c(`Affected Limb (AL)`, Group, TX)) %>%
  cbind(Treatment = treatment, Grouping = grouping) %>%
  filter(Patient != 39 & Patient != 6) %>% #Drop doges 39 and 6, not needed in the analysis
  pivot_longer(!c(Treatment, Patient, Time, Visit, Grouping), names_to = "Response", values_to = "Value")

clean_data_sh2 = raw_data_sh2 %>%
  rename(Time = `B1 - T1 - B2 - T2`, Patient = `Enroll #`) %>%
  mutate(Time = factor(Time,levels = c("B1","T1_1","T1_2",
                                         "B2", "T2_1", "T2_2"))) %>%
  group_by(Patient, Time) %>%
  summarise("SED_MIN/DAY" = mean(`SED_MIN/DAY`,na.rm = T),
            "LIGHT_MIN/DAY" = mean(`LIGHT_MIN/DAY`,na.rm = T),
            "VIG_MIN/DAY" = mean(`VIG_MIN/DAY`,na.rm = T),
            "Total Daily Activity Count" = mean(`Total Daily Activity Count`,na.rm = T)) %>%
  cbind(Treatment = treatment, Grouping = grouping) %>%
  filter(Patient != 39 & Patient != 6) %>%
  mutate(Visit = ifelse(Time == "B1", 2,
                        ifelse(Time == "T1_1", 3,
                        ifelse(Time == "T1_2", 4,
                        ifelse(Time == "B2", 5,
                        ifelse(Time == "T2_1", 6,
                        ifelse(Time == "T2_2", 7, 8))))))) %>%
  mutate(Time = ifelse(Time == "B1" | Time == "B2", "baseline",
                      ifelse(Time == "T1_1" | Time == "T2_1", "post1",
                      ifelse(Time == "T1_2" | Time == "T2_2", "post2", "intro"))))  %>%
  pivot_longer(!c(Treatment, Patient, Time, Visit, Grouping), names_to = "Response", values_to = "Value")

# Combine data
clean_data = rbind(clean_data_sh1, clean_data_sh2) %>%
              filter(Response %in% response_variables)
```

## Summary Statistics
```{r}
summary = clean_data %>%
      group_by(Response, Time, Treatment) %>%
        summarise(Min=min(Value, na.rm = T), 
                  Q1=quantile(Value, probs = 0.25, na.rm = T),
                  Median=median(Value, na.rm = T), 
                  Mean = mean(Value, na.rm = T), 
                  Q3=quantile(Value, probs = 0.75, na.rm = T),
                  Max=max(Value, na.rm = T), 
                  SD = sd(Value, na.rm = T),
                  N = sum(!is.na(Value))) %>%
  arrange(Response, Treatment)

summary2 = clean_data %>%
      group_by(Response, Time, Treatment, Visit) %>%
        summarise(Median=median(Value, na.rm = T), 
                  Mean = mean(Value, na.rm = T), 
                  SD = sd(Value, na.rm = T),
                  N = sum(!is.na(Value)), Grouping = Grouping) %>%
  arrange(Response, Treatment)

create_plots = function(input) {
  data = summary2 %>%
    filter(Response == input)
  
  p = ggplot(data, aes(x = Visit, y = Mean, color= Treatment, group = Grouping)) + 
    geom_line() + 
    geom_point() + 
    ylab(input) + 
    theme_minimal()
  return(p)
}

plot_list = lapply(response_variables, create_plots)
ggexport(plot_list, filename = "visit_plots.pdf")

```

## Summary plots
```{r}
create_boxplots = function(input) {
  data = clean_data %>%
    filter(Response == input)
  
  p = ggplot(data, aes(x = Time, y = Value, color= Treatment)) + 
    geom_boxplot() + 
    ylab(input) + 
    theme_minimal()
  return(p)
}

boxplot_list = lapply(response_variables, create_boxplots)
names(boxplot_list) = response_variables

# Save all plots in pdf (one plot per page)
all_plots = ggexport(boxplot_list, filename = "boxplots.pdf")
```

## Analysis

```{r}
fit_model = function(input) {
  data = clean_data %>%
       filter(Response == input)
  fit = lmerTest::lmer(Value ~ Time*Treatment + (1|Patient), data = data)
  return(fit)
}

model_list = map(response_variables, fit_model)
names(model_list) = response_variables

model_summary = lapply(model_list, stats::anova, type = 3)
names(model_summary) = response_variables

# Get a list of p-values from model summary
plist = as.data.frame(t(unlist(model_summary))) %>%
  select(matches(".Pr"))

# Find FDR adjusted p-values
plist_adjusted = p.adjust(plist, method = "fdr")

anova_df =  as.data.frame(do.call(rbind, model_summary)) %>%
  cbind(plist_adjusted) %>%
  rownames_to_column() %>%
  rename(Response = rowname, "Adj Pr(>F)" = plist_adjusted, "Raw Pr(>F)" = `Pr(>F)`)


# Get pairwise comparisons for models with evidence of a difference
emmeans_vars = as.vector(filter(anova_df, 
                                anova_df$`Adj Pr(>F)` <= 0.05)$Response) 

emmeans_vars = emmeans_vars[stringr::str_detect(emmeans_vars, "Treatment")]
emmeans_vars = emmeans_vars %>%
                  str_remove(".Time:Treatment") %>%
                  str_remove(".Treatment")

emmeans_list1 = map(model_list[names(model_list) %in% emmeans_vars], 
                   emmeans, ~Time|Treatment)
emmeans_list2 = map(model_list[names(model_list) %in% emmeans_vars], 
                   emmeans, ~Treatment|Time)

pair_list1 = map(emmeans_list1, contrast, "pairwise")
pair_list2 = map(emmeans_list2, contrast, "pairwise")

# Create a df for contrasts
contrast_df1 = matrix(ncol = 8)
colnames(contrast_df1) = c("contrast", "Treatment", "estimate",
                          "SE", "df", "t.ratio",  
                          "p.value",  "Response")
for (i in 1:length(pair_list1)) {
  rows = summary(pair_list1[[i]])
  rows = cbind(rows, Response = rep(names(pair_list1)[[i]], 3))
  contrast_df1 = rbind(contrast_df1, rows)
}
contrast_df1 = contrast_df1 %>%
  relocate("Response")

# Create a df for contrasts
contrast_df2 = matrix(ncol = 8)
colnames(contrast_df2) = c("contrast", "Time", "estimate",
                          "SE", "df", "t.ratio",  
                          "p.value",  "Response")
for (i in 1:length(pair_list2)) {
  rows = summary(pair_list2[[i]])
  rows = cbind(rows, Response = rep(names(pair_list2)[[i]], 3))
  contrast_df2 = rbind(contrast_df2, rows)
}
contrast_df2 = contrast_df2 %>%
  relocate("Response")

# Create sheets for result excel file
list_of_datasets <- list("Summary Statistics" = summary, 
                         "Mixed Model Results" = anova_df, 
                         "Pairwise Comparisons|Treatment" = contrast_df1[-1,],
                         "Pairwise Comparisons|Time" = contrast_df2[-1,])
write.xlsx(list_of_datasets, file = "results.xlsx")

## Checking assumptions
resid_plots = map(model_list, plot)
ggexport(resid_plots, filename = "residual_plots.pdf")
```


```{r}
# Checking log-transformed total daily activity count
total_act_data = clean_data %>%
  filter(Response == "Total Daily Activity Count") %>%
  mutate(Value = log(Value))

fit = lmerTest::lmer(Value ~ Time*Treatment + (1|Patient), data = total_act_data)
anova(fit)
plot(fit)
```

